version: "3.9"

services:
  wordpress:
    image: wordpress:6.7.2-php8.1-apache
    container_name: maa_wordpress_dev
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('FS_METHOD', 'direct');
    volumes:
      - wordpress_data:/var/www/html
      - ./plugin:/var/www/html/wp-content/plugins/my-ai-sales-assistant
    networks:
      - maa_net

  mysql:
    image: mysql:8.0
    container_name: maa_mysql_dev
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - maa_net

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: maa_phpmyadmin_dev
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8084:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 128M
    networks:
      - maa_net

  mongo:
    image: mongo:7
    container_name: maa_mongo_dev
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - mongo_data:/data/db
      - ./data/backup:/data/backup
    networks:
      - maa_net

  backend:
    image: node:20.12.2-alpine
    container_name: maa_backend_dev
    restart: unless-stopped
    working_dir: /app
    #user: "1000:1000"
    depends_on:
      - mongo
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      CORS_ORIGIN: http://localhost:8083
      MONGO_URI: mongodb://mongo:27017/dbsamsung_edu
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/logs/requests:/app/logs/requests
    networks:
      - maa_net

volumes:
  wordpress_data:
  mysql_data:
  mongo_data:

networks:
  maa_net:
    driver: bridge