#!/usr/bin/env bash
# Compose projects/alogweb/.env from environment variables.
#
# Meant for CI: the workflow passes GitHub Actions variables and secrets in, and
# this writes the file the compose stack reads. Run by hand and it will use
# whatever is exported in your shell.
#
#   ALOGWEB_ENV_FILE=/path/.env MYSQL_PASSWORD=... MYSQL_ROOT_PASSWORD=... ./scripts/write-env.sh
#
# Values are never echoed. Only names appear in the output, so a CI log shows
# what was configured without showing what it was set to.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${ALOGWEB_ENV_FILE:-$PROJECT_DIR/.env}"

log()  { printf '\n==> %s\n' "$*"; }
die()  { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

# Passwords have no sensible default: a stack that silently comes up with a
# guessable database password is worse than one that refuses to start.
: "${MYSQL_PASSWORD:?set MYSQL_PASSWORD (GitHub secret ALOGWEB_MYSQL_PASSWORD)}"
: "${MYSQL_ROOT_PASSWORD:?set MYSQL_ROOT_PASSWORD (GitHub secret ALOGWEB_MYSQL_ROOT_PASSWORD)}"

SITE_URL="${SITE_URL:-}"
[ -n "$SITE_URL" ] || die "set SITE_URL (GitHub variable ALOGWEB_SITE_URL)"

emit() {   # emit NAME DEFAULT
    local name="$1" default="${2-}" value
    value="$(printf '%s' "${!name-}")"
    [ -n "$value" ] || value="$default"
    printf '%s=%s\n' "$name" "$value"
}

TMP="$(mktemp "${TMPDIR:-/tmp}/alogweb-env.XXXXXX")"
chmod 600 "$TMP"
trap 'rm -f "$TMP"' EXIT

{
    printf '# Generated by scripts/write-env.sh - do not edit by hand.\n'
    printf '# Values come from GitHub Actions variables and secrets.\n'
    printf '# Written %s\n\n' "$(date -u '+%Y-%m-%d %H:%M:%SZ')"

    emit SITE_URL
    emit HTTP_PORT 8093
    emit HTTP_BIND_ADDRESS 0.0.0.0
    # Only read by docker-compose.ssl.yml, harmless until that overlay is used.
    emit HTTPS_PORT 443
    emit HTTPS_BIND_ADDRESS 0.0.0.0
    printf '\n'

    emit MYSQL_DATABASE alogweb_wordpress
    emit MYSQL_USER alogweb
    emit MYSQL_PASSWORD
    emit MYSQL_ROOT_PASSWORD
    emit WORDPRESS_TABLE_PREFIX apk_
    emit MYSQL_BIND_ADDRESS 127.0.0.1
    emit MYSQL_PORT 3317
    printf '\n'

    emit DISABLE_WP_CRON true
    emit WORDPRESS_DEBUG
    emit WP_AUTO_UPDATE_CORE minor
    emit ALOGWEB_WP_IMAGE 7.1-php8.2-fpm
    emit ALOGWEB_WPCLI_IMAGE cli-php8.2
    emit ALOGWEB_ADMIN_BAR 0
    printf '\n'

    emit ALOGWEB_MYSQL_VOLUME alogweb_mysql_data
    emit ALOGWEB_WORDPRESS_VOLUME alogweb_wordpress_data
    emit ALOGWEB_NGINX_LOG_VOLUME alogweb_nginx_logs
    emit ALOGWEB_NGINX_CACHE_VOLUME alogweb_nginx_cache
    emit ALOGWEB_NGINX_PAGE_CACHE_VOLUME alogweb_nginx_page_cache
    emit ALOGWEB_CERTBOT_WEBROOT_VOLUME alogweb_certbot_webroot
    emit ALOGWEB_NETWORK alogweb_net
    emit CONTAINER_PREFIX maa_alogweb
    # Compose identifies a stack by this, not by container names. A second
    # checkout needs its own value or it takes over the first one's containers.
    emit COMPOSE_PROJECT_NAME maa-alogweb
    emit ALOGWEB_BACKUP_KEEP_DAYS 14
    printf '\n'

    emit SITE_CONTACT_EMAIL
    emit CONTACT_FORWARD_TO
    emit CONTACT_FROM_EMAIL
    emit CONTACT_SMTP_HOST
    emit CONTACT_SMTP_PORT 587
    emit CONTACT_SMTP_USER
    emit CONTACT_SMTP_PASSWORD
    emit CONTACT_SMTP_USE_TLS true
    emit CONTACT_SMTP_TLS_VERIFY true
    emit CONTACT_RATE_LIMIT_SECONDS 60
    emit CONTACT_MIN_SUBMIT_SECONDS 3
    emit CONTACT_ROTATION_TOLERANCE 8
} > "$TMP"

mkdir -p "$(dirname "$TARGET")"
mv "$TMP" "$TARGET"
chmod 600 "$TARGET"
trap - EXIT

log "Wrote $TARGET ($(grep -c '=' "$TARGET") settings)"
printf '    set from the environment: %s\n' \
    "$(grep -oE '^[A-Z_]+=.+' "$TARGET" | cut -d= -f1 | tr '\n' ' ')"
printf '    left empty: %s\n' \
    "$(grep -oE '^[A-Z_]+=$' "$TARGET" | cut -d= -f1 | tr '\n' ' ' || true)"
